package br.com.douglas.ds.springmysqldata;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

@Controller //This mean that this class is a Controller
@RequestMapping(path="/user") //This means URL's  starts with /user (After Application path)
public class MainController {
    @Autowired //This means to get the bean called userRepository
                // Wich is auto-generated by Spring,this is used to handle the data
    private UserRepository userRepository;

    @GetMapping(path="/add")
    @ResponseBody
    public String addNewUser(@RequestParam String name,
                      @RequestParam String email) {
        User user = new User();
        user.setName(name);
        user.setEmail(email);
        userRepository.save(user);
        return "Saved";
    }

    @GetMapping(path="/all")
    @ResponseBody
    public Iterable<User> getAllUsers() {
        //This return a JSON or XML with the users
        return userRepository.findAll();
    }

    @GetMapping(path="/del")
    @ResponseBody
    public String deleteUser(@RequestParam Integer id) {
        User user = new User();
        user.setId(id);
        userRepository.delete(user);
        return "Deleted";
    }
}
